name: "Continous integration and deployment"

#Specife Events to triger this Workflows
on:
  push:
    branches:
      - deploy-to-ec2
  pull_request:
    branches:
      - deploy-to-ec2
  workflow_dispatch:

jobs:
  build-job:
    runs-on:
      - ubuntu-latest
    steps:
      - name: "clonner le code sur le runner"
        uses: actions/checkout@v3
      - name: "installer java environemment "

        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          run: java --version
      - name: "test the src code"
        # run some unit test
        run: mvn test
      - name: "packging the code end dependecies in jar file"
        run: mvn package

      - name: hosting the package code in docker registery
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/java-spring:latest